#!/bin/bash

PASSWORD='pbkdf2_sha256$260000$tgFiPBt6vgUNwsGIP0YExI$ItKfUyMV2tAhGZTuurW+gjy7HRm0ujV1w65nLf6u+ms='
EMAIL='jflabonte@poka.io'
SCHEMA="public"

if [ -n "$1" ]; then
    SCHEMA=$1
fi

PGPASSWD="poka_dev" psql -v ON_ERROR_STOP=1 --username "poka_dev" --host localhost --dbname "poka_dev" -c "UPDATE $SCHEMA.auth_user SET password = '$PASSWORD', email = '$EMAIL';"