#!/usr/bin/env python3
import argparse
import json
import urllib.request

SERVER_INFO_URL = "https://{instance_name}.poka.io/api/v2.2/public/server-info/"

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Find the infra name of an instance.")
    parser.add_argument("name", type=str, help="The instance name")

    args = parser.parse_args()
    instance_name = args.name

    url = SERVER_INFO_URL.format(instance_name=instance_name)

    with urllib.request.urlopen(url) as response:
        data = json.loads(response.read())
        print(data.get("client_code", "Unknown"))
