#!/usr/bin/env python3
from argparse import ArgumentParser
from pathlib import Path
import shutil
import subprocess

PATH_TO_BACKUP = Path.joinpath(Path.home(), Path("Development/Poka/projects/poka_backend/docker-compose/backup/")

def get_file_in_s3(s3_path):
    subprocess.run(["aws", "s3", "cp", s3_path, "."])

def move_file(file_name):
    shutie.move_file(file_name, Path.joinpath(self.PATH_TO_BACKUP, file_name)

def build_argument_parser():
    args = ArgumentParser()
    args.add_argument(
        "--s3_path",
        type=str,
        help="The Path of your file on S3",
    )
    return args


if __name__ in "__main__":
    argument_parser = build_argument_parser()
